<h2>Chuẩn bị tập Dataset dùng cho xây dựng model</h2>

<h5>Phần này sẽ kết hợp các table cần thiết thành một table có các input và output để xây dựng mô hình dự đoán</h5>

In [94]:
import pandas as pd

In [95]:
fbref_matchstats = pd.read_csv("./fbref_modified/fbref_MatchStats_modified.csv")
fbref_matchinfos = pd.read_csv("./fbref_modified/fbref_matchinfos_modified.csv")

In [96]:
fbref_matchstats.head(6)

,Match_Id,Team,Is_Home_Team,Manager,Captain,Formation,Possession,Fouls,Corners,Crosses,...,GCA,Passes_Cmp,Passes_Att,Passes_Cmp_Percentage,Passes_PrgP,Carries,Carries_PrgC,Take_Ons_Att,Take_Ons_Succ,Score
0,db4d7668,Watford,Yes,Javi Gracia,Troy Deeney,4222,49,10,7,22,...,1,361,467,77.3,43,295,21,8,5,1
1,db4d7668,West Ham United,No,Manuel Pellegrini,Mark Noble,4141,51,10,2,9,...,6,426,492,86.6,32,347,31,28,23,4
2,d4360fcd,Burnley,Yes,Sean Dyche,James Tarkowski,442,55,11,6,37,...,2,328,454,72.2,37,261,16,1,1,1
3,d4360fcd,Brighton & Hove Albion,No,Graham Potter,Lewis Dunk,3412,45,11,7,19,...,4,279,377,74.0,29,288,18,11,5,2
4,b6b1209d,Newcastle United,Yes,Steve Bruce,Jonjo Shelvey,352,26,11,2,7,...,2,193,297,65.0,8,214,5,6,3,1
5,b6b1209d,Liverpool,No,Jürgen Klopp,James Milner,433,74,5,4,17,...,6,742,844,87.9,59,780,21,30,13,3

In [97]:
fbref_matchstats = pd.merge(fbref_matchstats, fbref_matchinfos[['Match_Id', 'Match_Date']], on='Match_Id')
fbref_matchstats.head(6)

,Match_Id,Team,Is_Home_Team,Manager,Captain,Formation,Possession,Fouls,Corners,Crosses,...,Passes_Cmp,Passes_Att,Passes_Cmp_Percentage,Passes_PrgP,Carries,Carries_PrgC,Take_Ons_Att,Take_Ons_Succ,Score,Match_Date
0,db4d7668,Watford,Yes,Javi Gracia,Troy Deeney,4222,49,10,7,22,...,361,467,77.3,43,295,21,8,5,1,2019-05-12
1,db4d7668,West Ham United,No,Manuel Pellegrini,Mark Noble,4141,51,10,2,9,...,426,492,86.6,32,347,31,28,23,4,2019-05-12
2,d4360fcd,Burnley,Yes,Sean Dyche,James Tarkowski,442,55,11,6,37,...,328,454,72.2,37,261,16,1,1,1,2020-07-26
3,d4360fcd,Brighton & Hove Albion,No,Graham Potter,Lewis Dunk,3412,45,11,7,19,...,279,377,74.0,29,288,18,11,5,2,2020-07-26
4,b6b1209d,Newcastle United,Yes,Steve Bruce,Jonjo Shelvey,352,26,11,2,7,...,193,297,65.0,8,214,5,6,3,1,2020-07-26
5,b6b1209d,Liverpool,No,Jürgen Klopp,James Milner,433,74,5,4,17,...,742,844,87.9,59,780,21,30,13,3,2020-07-26

<h4>1. Định dạng MatchStat table</h4>

Tách ra các trận cho Home Team và Away Team

In [98]:
match_home = pd.DataFrame()
match_home = fbref_matchstats.iloc[0:len(fbref_matchstats):2]

match_away = pd.DataFrame()
match_away = fbref_matchstats.iloc[1:len(fbref_matchstats):2]

In [99]:
match_home.head(4)

,Match_Id,Team,Is_Home_Team,Manager,Captain,Formation,Possession,Fouls,Corners,Crosses,...,Passes_Cmp,Passes_Att,Passes_Cmp_Percentage,Passes_PrgP,Carries,Carries_PrgC,Take_Ons_Att,Take_Ons_Succ,Score,Match_Date
0,db4d7668,Watford,Yes,Javi Gracia,Troy Deeney,4222,49,10,7,22,...,361,467,77.3,43,295,21,8,5,1,2019-05-12
2,d4360fcd,Burnley,Yes,Sean Dyche,James Tarkowski,442,55,11,6,37,...,328,454,72.2,37,261,16,1,1,1,2020-07-26
4,b6b1209d,Newcastle United,Yes,Steve Bruce,Jonjo Shelvey,352,26,11,2,7,...,193,297,65.0,8,214,5,6,3,1,2020-07-26
6,a3f59c8e,West Ham United,Yes,David Moyes,Mark Noble,4231,62,16,0,10,...,425,527,80.6,42,420,12,11,5,1,2020-07-26

In [100]:
match_away.head(4)

,Match_Id,Team,Is_Home_Team,Manager,Captain,Formation,Possession,Fouls,Corners,Crosses,...,Passes_Cmp,Passes_Att,Passes_Cmp_Percentage,Passes_PrgP,Carries,Carries_PrgC,Take_Ons_Att,Take_Ons_Succ,Score,Match_Date
1,db4d7668,West Ham United,No,Manuel Pellegrini,Mark Noble,4141,51,10,2,9,...,426,492,86.6,32,347,31,28,23,4,2019-05-12
3,d4360fcd,Brighton & Hove Albion,No,Graham Potter,Lewis Dunk,3412,45,11,7,19,...,279,377,74.0,29,288,18,11,5,2,2020-07-26
5,b6b1209d,Liverpool,No,Jürgen Klopp,James Milner,433,74,5,4,17,...,742,844,87.9,59,780,21,30,13,3,2020-07-26
7,a3f59c8e,Aston Villa,No,Dean Smith,Jack Grealish,4141,38,13,7,14,...,217,323,67.2,18,193,11,9,3,1,2020-07-26

Lược bỏ biến Is_Home_Team

In [101]:
match_home = match_home.drop('Is_Home_Team', axis=1)
match_away = match_away.drop('Is_Home_Team', axis=1)

Đổi các tên attribute

In [102]:
match_home.columns = ['Match_Id',
                        'Home_Team', 'Home_Manager', 'Home_Captain',
                        'Home_Formation', 'Home_Possession', 'Home_Fouls', 'Home_Corners', 'Home_Crosses',
                        'Home_Aerials_Won', 'Home_Clearances', 'Home_Offsides', 'Home_Goal_Kicks',
                        'Home_Throw_Ins', 'Home_Long_Balls', 'Home_Total_Players_Stats', 'Home_Minutes',
                        'Home_Gls', 'Home_Ast', 'Home_PK', 'Home_PK_Att',
                        'Home_Sh','Home_SoT', 'Home_CrdY', 'Home_CrdR',
                        'Home_Touches','Home_Tkl','Home_Int','Home_Blocks',
                        'Home_xG','Home_npxG', 'Home_xAG',
                        'Home_SCA', 'Home_GCA',
                        'Home_Cmp_Passes', 'Home_Att_Passes', 'Home_Cmp_percent_Passes', 'Home_PrgP_Passes',
                        'Home_Carries_Carries', 'Home_PrgC_Carries', 
                        'Home_Att_Take_Ons', 'Home_Succ_Take_Ons',
                        'Home_Score',
                        'Match_Date']

In [103]:
match_away.columns = ['Match_Id',
                        'Away_Team', 'Away_Manager', 'Away_Captain',
                        'Away_Formation', 'Away_Possession', 'Away_Fouls', 'Away_Corners', 'Away_Crosses',
                        'Away_Aerials_Won', 'Away_Clearances', 'Away_Offsides', 'Away_Goal_Kicks',
                        'Away_Throw_Ins', 'Away_Long_Balls', 'Away_Total_Players_Stats', 'Away_Minutes',
                        'Away_Gls', 'Away_Ast', 'Away_PK', 'Away_PK_Att',
                        'Away_Sh','Away_SoT', 'Away_CrdY', 'Away_CrdR',
                        'Away_Touches','Away_Tkl','Away_Int','Away_Blocks',
                        'Away_xG','Away_npxG', 'Away_xAG',
                        'Away_SCA', 'Away_GCA',
                        'Away_Cmp_Passes', 'Away_Att_Passes', 'Away_Cmp_percent_Passes', 'Away_PrgP_Passes',
                        'Away_Carries_Carries', 'Away_PrgC_Carries', 
                        'Away_Att_Take_Ons', 'Away_Succ_Take_Ons',
                        'Away_Score',
                        'Match_Date']

In [104]:
match_merge = pd.merge(match_home, match_away, on=['Match_Id', 'Match_Date'], how='inner')
match_merge.head(3)

,Match_Id,Home_Team,Home_Manager,Home_Captain,Home_Formation,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,Home_Aerials_Won,...,Away_GCA,Away_Cmp_Passes,Away_Att_Passes,Away_Cmp_percent_Passes,Away_PrgP_Passes,Away_Carries_Carries,Away_PrgC_Carries,Away_Att_Take_Ons,Away_Succ_Take_Ons,Away_Score
0,db4d7668,Watford,Javi Gracia,Troy Deeney,4222,49,10,7,22,12,...,6,426,492,86.6,32,347,31,28,23,4
1,d4360fcd,Burnley,Sean Dyche,James Tarkowski,442,55,11,6,37,21,...,4,279,377,74.0,29,288,18,11,5,2
2,b6b1209d,Newcastle United,Steve Bruce,Jonjo Shelvey,352,26,11,2,7,15,...,6,742,844,87.9,59,780,21,30,13,3

Sắp xếp lại các attribute

In [105]:
match_merge = match_merge.loc[:,['Match_Id', 'Match_Date',
                                'Home_Team', 'Home_Manager', 'Home_Captain',
                                'Home_Formation', 'Home_Possession', 'Home_Fouls', 'Home_Corners', 'Home_Crosses',
                                'Home_Aerials_Won', 'Home_Clearances', 'Home_Offsides', 'Home_Goal_Kicks',
                                'Home_Throw_Ins', 'Home_Long_Balls', 'Home_Total_Players_Stats', 'Home_Minutes',
                                'Home_Gls', 'Home_Ast', 'Home_PK', 'Home_PK_Att',
                                'Home_Sh','Home_SoT', 'Home_CrdY', 'Home_CrdR',
                                'Home_Touches','Home_Tkl','Home_Int','Home_Blocks',
                                'Home_xG','Home_npxG', 'Home_xAG',
                                'Home_SCA', 'Home_GCA',
                                'Home_Cmp_Passes', 'Home_Att_Passes', 'Home_Cmp_percent_Passes', 'Home_PrgP_Passes',
                                'Home_Carries_Carries', 'Home_PrgC_Carries', 
                                'Home_Att_Take_Ons', 'Home_Succ_Take_Ons',
                                'Away_Team', 'Away_Manager', 'Away_Captain',
                                'Away_Formation', 'Away_Possession', 'Away_Fouls', 'Away_Corners', 'Away_Crosses',
                                'Away_Aerials_Won', 'Away_Clearances', 'Away_Offsides', 'Away_Goal_Kicks',
                                'Away_Throw_Ins', 'Away_Long_Balls', 'Away_Total_Players_Stats', 'Away_Minutes',
                                'Away_Gls', 'Away_Ast', 'Away_PK', 'Away_PK_Att',
                                'Away_Sh','Away_SoT', 'Away_CrdY', 'Away_CrdR',
                                'Away_Touches','Away_Tkl','Away_Int','Away_Blocks',
                                'Away_xG','Away_npxG', 'Away_xAG',
                                'Away_SCA', 'Away_GCA',
                                'Away_Cmp_Passes', 'Away_Att_Passes', 'Away_Cmp_percent_Passes', 'Away_PrgP_Passes',
                                'Away_Carries_Carries', 'Away_PrgC_Carries', 
                                'Away_Att_Take_Ons', 'Away_Succ_Take_Ons',
                                'Home_Score','Away_Score']]
match_merge

,Match_Id,Match_Date,Home_Team,Home_Manager,Home_Captain,Home_Formation,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,...,Away_Cmp_Passes,Away_Att_Passes,Away_Cmp_percent_Passes,Away_PrgP_Passes,Away_Carries_Carries,Away_PrgC_Carries,Away_Att_Take_Ons,Away_Succ_Take_Ons,Home_Score,Away_Score
0,db4d7668,2019-05-12,Watford,Javi Gracia,Troy Deeney,4222,49,10,7,22,...,426,492,86.6,32,347,31,28,23,1,4
1,d4360fcd,2020-07-26,Burnley,Sean Dyche,James Tarkowski,442,55,11,6,37,...,279,377,74.0,29,288,18,11,5,1,2
2,b6b1209d,2020-07-26,Newcastle United,Steve Bruce,Jonjo Shelvey,352,26,11,2,7,...,742,844,87.9,59,780,21,30,13,1,3
3,a3f59c8e,2020-07-26,West Ham United,David Moyes,Mark Noble,4231,62,16,0,10,...,217,323,67.2,18,193,11,9,3,1,1
4,9cca4ba0,2020-07-26,Chelsea,Frank Lampard,César Azpilicueta,343,62,10,3,11,...,281,410,68.5,29,232,9,23,8,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,82702941,2022-08-06,Leeds United,Jesse Marsch,Patrick Bamford,4231,40,13,6,20,...,502,597,84.1,44,507,20,41,25,2,1
1986,1ac96eb4,2022-08-06,Newcastle United,Eddie Howe,Kieran Trippier,433,61,9,11,25,...,243,342,71.1,16,202,12,17,5,2,0
1987,09d8a999,2022-08-06,Tottenham Hotspur,Antonio Conte,Hugo Lloris,343,58,11,10,24,...,351,445,78.9,31,299,12,18,9,4,1
1988,6713c1dc,2022-08-06,Fulham,Marco Silva,Tim Ream,4231,33,7,4,19,...,514,675,76.1,53,418,11,17,4,2,2
1989,e62f6e78,2022-08-05,Crystal Palace,Patrick Vieira,Marc Guéhi,4231,56,16,3,19,...,378,469,80.6,40,359,15,17,13,0,2

<h4>2. Thay tất cả statistics match bằng trung bình cộng của 2 trận của team trước đó</h4>

Sắp xếp các match theo thứ tự giảm dần Match_Date

In [106]:
match_merge_desc = match_merge.sort_values(by='Match_Date', ascending=False)
match_merge_desc

,Match_Id,Match_Date,Home_Team,Home_Manager,Home_Captain,Home_Formation,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,...,Away_Cmp_Passes,Away_Att_Passes,Away_Cmp_percent_Passes,Away_PrgP_Passes,Away_Carries_Carries,Away_PrgC_Carries,Away_Att_Take_Ons,Away_Succ_Take_Ons,Home_Score,Away_Score
1521,8c6293a3,2023-10-23,Tottenham Hotspur,Ange Postecoglou,Son Heung-min,4231,55,10,3,11,...,419,513,81.7,27,387,11,24,12,2,0
1522,7efcc598,2023-10-22,Aston Villa,Unai Emery,John McGinn,442,58,8,8,20,...,312,395,79.0,41,282,18,22,14,4,1
1523,d95b42eb,2023-10-21,Sheffield United,Paul Heckingbottom,Oliver Norwood,442,38,12,5,15,...,471,603,78.1,36,471,16,16,9,1,2
1528,21625dde,2023-10-21,Newcastle United,Eddie Howe,Jamaal Lascelles,433,59,7,6,18,...,329,427,77.0,32,297,10,14,8,4,0
1530,e747ddb3,2023-10-21,Liverpool,Jürgen Klopp,Virgil van Dijk,433,77,9,12,27,...,131,244,53.7,12,103,4,21,12,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,8dc8eaeb,2018-08-11,Wolverhampton Wanderers,Nuno Espírito Santo,Conor Coady,343,58,8,3,25,...,326,448,72.8,23,306,13,7,2,2,2
754,d82a37a7,2018-08-11,Huddersfield Town,David Wagner,Jonathan Hogg,3511,38,9,2,23,...,615,701,87.7,32,464,29,21,17,0,3
756,352f5574,2018-08-11,Bournemouth,Eddie Howe,Andrew Surman,442,63,11,7,11,...,191,327,58.4,27,179,11,17,9,2,0
757,30875601,2018-08-11,Fulham,Slaviša Jokanović,Tom Cairney,433,65,9,5,32,...,286,388,73.7,36,233,19,21,12,0,2
759,3ae83896,2018-08-10,Manchester United,José Mourinho,Paul Pogba,433,47,11,2,12,...,475,598,79.4,55,476,24,18,9,2,1

In [107]:
list_all_teams = match_merge_desc['Home_Team'].unique()
list_all_teams

array(['Tottenham Hotspur', 'Aston Villa', 'Sheffield United',
       'Newcastle United', 'Liverpool', 'Bournemouth', 'Chelsea',
       'Brentford', 'Nottingham Forest', 'Manchester City', 'Arsenal',
       'Brighton & Hove Albion', 'Wolverhampton Wanderers',
       'West Ham United', 'Everton', 'Luton Town', 'Manchester United',
       'Burnley', 'Fulham', 'Crystal Palace', 'Leicester City',
       'Southampton', 'Leeds United', 'Norwich City', 'Watford',
       'West Bromwich Albion', 'Huddersfield Town', 'Cardiff City'],
      dtype=object)

Thay đổi các statistic

In [108]:
for team in list_all_teams:

    this_team = match_merge_desc[(match_merge_desc['Home_Team'] == team) | 
                (match_merge_desc['Away_Team'] == team)]

    for i in range(0, len(this_team)-2):
    
        if(this_team.iloc[i,this_team.columns.get_loc('Home_Team')] == team):

            for j in range(6, 43):

                list_2_elements = []

                for k in range(i+1, i+3):
                    if(this_team.iloc[k,this_team.columns.get_loc('Home_Team')] == team):

                        list_2_elements.append(this_team.iloc[k, j])

                    if(this_team.iloc[k,this_team.columns.get_loc('Away_Team')] == team):

                        list_2_elements.append(this_team.iloc[k, j+41])
            
                match_id = this_team.iloc[i,this_team.columns.get_loc('Match_Id')]

                match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id, 
                                match_merge_desc.columns[j]] = sum(list_2_elements) / 2
            
        if(this_team.iloc[i,this_team.columns.get_loc('Away_Team')] == team):

            for j in range(47, 84):
  
                list_2_elements = []

                for k in range(i+1, i+3):
                    if(this_team.iloc[k,this_team.columns.get_loc('Home_Team')] == team):

                        list_2_elements.append(this_team.iloc[k, j-41])

                    if(this_team.iloc[k,this_team.columns.get_loc('Away_Team')] == team):

                        list_2_elements.append(this_team.iloc[k, j])
            
                match_id = this_team.iloc[i,this_team.columns.get_loc('Match_Id')]

                match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id, 
                                match_merge_desc.columns[j]] = sum(list_2_elements) / 2   

    print(team)

C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '8.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '11.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '6.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '24.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '40.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '19.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '21.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '14.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '35.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '565.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '660.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '71.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '58.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '7.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '19.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '18.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '6.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '4.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '25.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '8.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '516.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '56.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '439.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '22.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '21.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '61.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '7.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '11.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '43.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '634.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '12.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '486.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '5.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '686.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '40.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '15.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '12.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '606.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '4.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,
C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '988.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,

C:\Users\ben\AppData\Local\Temp\ipykernel_1424\723529084.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '975.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  match_merge_desc.loc[match_merge_desc['Match_Id'] == match_id,

Tottenham Hotspur
Aston Villa
Sheffield United
Newcastle United
Liverpool
Bournemouth
Chelsea
Brentford
Nottingham Forest
Manchester City
Arsenal
Brighton & Hove Albion
Wolverhampton Wanderers
West Ham United
Everton
Luton Town
Manchester United
Burnley
Fulham
Crystal Palace
Leicester City
Southampton
Leeds United
Norwich City
Watford
West Bromwich Albion
Huddersfield Town
Cardiff City

In [109]:
match_merge_desc

,Match_Id,Match_Date,Home_Team,Home_Manager,Home_Captain,Home_Formation,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,...,Away_Cmp_Passes,Away_Att_Passes,Away_Cmp_percent_Passes,Away_PrgP_Passes,Away_Carries_Carries,Away_PrgC_Carries,Away_Att_Take_Ons,Away_Succ_Take_Ons,Home_Score,Away_Score
1521,8c6293a3,2023-10-23,Tottenham Hotspur,Ange Postecoglou,Son Heung-min,4231,65.0,9.0,8.5,21.0,...,487.5,599.0,81.25,47.0,434.5,27.5,15.0,8.5,2,0
1522,7efcc598,2023-10-22,Aston Villa,Unai Emery,John McGinn,442,46.0,14.0,5.5,18.5,...,348.0,443.0,77.20,33.5,345.5,20.0,11.5,7.5,4,1
1523,d95b42eb,2023-10-21,Sheffield United,Paul Heckingbottom,Oliver Norwood,442,44.0,9.5,4.0,14.5,...,608.0,721.5,84.15,76.0,527.5,27.0,20.0,10.5,1,2
1528,21625dde,2023-10-21,Newcastle United,Eddie Howe,Jamaal Lascelles,433,58.5,12.5,3.5,15.5,...,324.5,404.5,76.50,27.0,276.5,13.0,20.0,9.5,4,0
1530,e747ddb3,2023-10-21,Liverpool,Jürgen Klopp,Virgil van Dijk,433,45.0,18.5,3.0,9.5,...,417.0,546.0,76.10,40.0,358.5,21.0,25.0,11.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,8dc8eaeb,2018-08-11,Wolverhampton Wanderers,Nuno Espírito Santo,Conor Coady,343,58.0,8.0,3.0,25.0,...,326.0,448.0,72.80,23.0,306.0,13.0,7.0,2.0,2,2
754,d82a37a7,2018-08-11,Huddersfield Town,David Wagner,Jonathan Hogg,3511,38.0,9.0,2.0,23.0,...,615.0,701.0,87.70,32.0,464.0,29.0,21.0,17.0,0,3
756,352f5574,2018-08-11,Bournemouth,Eddie Howe,Andrew Surman,442,63.0,11.0,7.0,11.0,...,191.0,327.0,58.40,27.0,179.0,11.0,17.0,9.0,2,0
757,30875601,2018-08-11,Fulham,Slaviša Jokanović,Tom Cairney,433,65.0,9.0,5.0,32.0,...,286.0,388.0,73.70,36.0,233.0,19.0,21.0,12.0,0,2
759,3ae83896,2018-08-10,Manchester United,José Mourinho,Paul Pogba,433,47.0,11.0,2.0,12.0,...,475.0,598.0,79.40,55.0,476.0,24.0,18.0,9.0,2,1

Xóa các match không có statistic của các team 2 match trước

In [110]:
list_remove_matchs = []

In [111]:
for team in list_all_teams:

    this_team = match_merge_desc[(match_merge_desc['Home_Team'] == team) | 
                (match_merge_desc['Away_Team'] == team)]
    
    match_id_1 = this_team.iloc[len(this_team)-1,this_team.columns.get_loc('Match_Id')]
    match_id_2 = this_team.iloc[len(this_team)-2,this_team.columns.get_loc('Match_Id')]
    #
    list_remove_matchs.append(match_id_1)
    list_remove_matchs.append(match_id_2)
    #Cần chếch
    match_merge_desc = match_merge_desc[(match_merge_desc['Match_Id'] != match_id_1) & (match_merge_desc['Match_Id'] != match_id_2)]

In [112]:
match_merge_desc

,Match_Id,Match_Date,Home_Team,Home_Manager,Home_Captain,Home_Formation,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,...,Away_Cmp_Passes,Away_Att_Passes,Away_Cmp_percent_Passes,Away_PrgP_Passes,Away_Carries_Carries,Away_PrgC_Carries,Away_Att_Take_Ons,Away_Succ_Take_Ons,Home_Score,Away_Score
1521,8c6293a3,2023-10-23,Tottenham Hotspur,Ange Postecoglou,Son Heung-min,4231,65.0,9.0,8.5,21.0,...,487.5,599.0,81.25,47.0,434.5,27.5,15.0,8.5,2,0
1522,7efcc598,2023-10-22,Aston Villa,Unai Emery,John McGinn,442,46.0,14.0,5.5,18.5,...,348.0,443.0,77.20,33.5,345.5,20.0,11.5,7.5,4,1
1523,d95b42eb,2023-10-21,Sheffield United,Paul Heckingbottom,Oliver Norwood,442,44.0,9.5,4.0,14.5,...,608.0,721.5,84.15,76.0,527.5,27.0,20.0,10.5,1,2
1528,21625dde,2023-10-21,Newcastle United,Eddie Howe,Jamaal Lascelles,433,58.5,12.5,3.5,15.5,...,324.5,404.5,76.50,27.0,276.5,13.0,20.0,9.5,4,0
1530,e747ddb3,2023-10-21,Liverpool,Jürgen Klopp,Virgil van Dijk,433,45.0,18.5,3.0,9.5,...,417.0,546.0,76.10,40.0,358.5,21.0,25.0,11.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,f74a4680,2018-09-01,Manchester City,Pep Guardiola,David Silva,4132,73.5,8.5,9.5,27.0,...,180.0,293.0,61.85,15.5,157.5,6.5,8.5,2.5,2,1
726,95fc9c84,2018-09-01,Chelsea,Maurizio Sarri,César Azpilicueta,433,71.0,10.0,5.0,19.0,...,301.0,397.0,75.75,40.5,293.0,22.0,18.5,9.0,2,0
727,51055c21,2018-09-01,Brighton & Hove Albion,Chris Hughton,Lewis Dunk,4411,32.5,15.0,4.0,12.0,...,442.5,536.0,82.40,38.5,273.0,22.5,12.5,7.5,2,2
734,db5e61cc,2018-08-25,Liverpool,Jürgen Klopp,James Milner,433,63.5,13.5,6.0,22.0,...,261.5,374.0,69.20,23.0,221.5,9.0,7.0,4.5,1,0
739,a25a3f33,2018-08-25,Wolverhampton Wanderers,Nuno Espírito Santo,Conor Coady,343,57.5,8.0,6.0,27.0,...,612.0,703.5,86.35,56.5,577.0,41.0,19.0,13.5,1,1

<h4>3. Thêm thông số Attack, Midfield, Defense dựa vào Player_Position và Player_Overall_Rating cho mỗi match</h4>

Nhập vào statistic của từng player trong mỗi match

In [140]:
matchsquad_players = pd.read_csv("./merge/matchsquad_players_completed.csv")

In [141]:
matchsquad_players

,Match_Id,Match_Date,Team,Player_Name,Player_Kitnum,Is_Sub,Sofifa_Id,Player_Position,Player_Overall_Rating,Player_Update_Date
0,db4d7668,2019-05-12,Watford,Ben Foster,26,No,163155.0,GK,79.0,2019-05-02
1,db4d7668,2019-05-12,Watford,Gerard Deulofeu,7,No,193061.0,LM CAM,80.0,2019-05-02
2,db4d7668,2019-05-12,Watford,Troy Deeney,9,No,183125.0,ST,78.0,2019-05-02
3,db4d7668,2019-05-12,Watford,Craig Cathcart,15,No,177578.0,CB,74.0,2019-05-02
4,db4d7668,2019-05-12,Watford,Abdoulaye Doucouré,16,No,208135.0,CDM CM,81.0,2019-05-02
...,...,...,...,...,...,...,...,...,...,...
76289,e62f6e78,2022-08-05,Arsenal,Cédric Soares,17,Yes,201118.0,RB,75.0,2022-07-06
76290,e62f6e78,2022-08-05,Arsenal,Nicolas Pépé,19,Yes,226110.0,RM,80.0,2022-07-06
76291,e62f6e78,2022-08-05,Arsenal,Albert Sambi Lokonga,23,Yes,241928.0,CM CDM,75.0,2022-07-06
76292,e62f6e78,2022-08-05,Arsenal,Reiss Nelson,24,Yes,231448.0,RW LW,74.0,2023-10-04
76293,e62f6e78,2022-08-05,Arsenal,Mohamed Elneny,25,Yes,211454.0,CDM CM,76.0,2022-07-06

Loại bỏ các match không có statistic của 2 match trước đã lưu trong list

In [142]:
for match in list_remove_matchs:
    matchsquad_players = matchsquad_players[matchsquad_players['Match_Id'] != match]

In [143]:
import numpy as np

Qui định các các Position ứng với 3 Lines: Attack, Midfield, Defense

In [144]:
attack_line = ["LS", "ST", "RS","LW", "LF", "CF", "RF", "RW"]
midfield_line = ["LAM", "CAM", "RAM","LM", "LCM", "CM", "RCM", "RM","LDM", "CDM", "RDM"]
defense_line = ["LB", "LCB", "CB", "RCB", "RB","LWB","RWB"]

In [145]:
new_attrs = pd.DataFrame({'Match_Id': [],
                        'Home_Attack': [],
                        'Home_Midfield': [],
                        'Home_Defense': [],
                        'Away_Attack': [],
                        'Away_Midfield': [],
                        'Away_Defense': []})
atr_match_id = []
atr_home_attack = []
atr_home_midfield = []
atr_home_defense = []
atr_away_attack = []
atr_away_midfield = []
atr_away_defense = []

In [146]:
for i in range(0, len(match_merge_desc)):

    match_id = match_merge_desc.iloc[i, match_merge_desc.columns.get_loc('Match_Id')]
    current_match = matchsquad_players[matchsquad_players['Match_Id'] == match_id]

    home_team = match_merge_desc.iloc[i, match_merge_desc.columns.get_loc('Home_Team')]
    away_team = match_merge_desc.iloc[i, match_merge_desc.columns.get_loc('Away_Team')]
    #

    list_home_attack = []
    list_home_midfield = []
    list_home_defense = []
    list_away_attack = []
    list_away_midfield = []
    list_away_defense = []

    for player in current_match.itertuples(index=False):

        if not np.isnan(player.Sofifa_Id):
            player_positions = player.Player_Position.split(' ')
            overall_rating = player.Player_Overall_Rating
        #home_team
        if (player.Team == home_team) and not np.isnan(player.Sofifa_Id):

            for position in player_positions:
                if (position in attack_line):
                    list_home_attack.append(overall_rating)
                if (position in midfield_line):
                    list_home_midfield.append(overall_rating)
                if (position in defense_line):
                    list_home_defense.append(overall_rating)
        #away_team
        if (player.Team == away_team) and not np.isnan(player.Sofifa_Id):

            for position in player_positions:
                if (position in attack_line):
                    list_away_attack.append(overall_rating)
                if (position in midfield_line):
                    list_away_midfield.append(overall_rating)
                if (position in defense_line):
                    list_away_defense.append(overall_rating)

    atr_match_id.append(match_id)
    atr_home_attack.append(sum(list_home_attack) / len(list_home_attack))
    atr_home_midfield.append(sum(list_home_midfield) / len(list_home_midfield))
    atr_home_defense.append(sum(list_home_defense) / len(list_home_defense))
    atr_away_attack.append(sum(list_away_attack) / len(list_away_attack))
    atr_away_midfield.append(sum(list_away_midfield) / len(list_away_midfield))
    atr_away_defense.append(sum(list_away_defense) / len(list_away_defense))

In [147]:
new_attrs['Match_Id'] = atr_match_id
new_attrs['Home_Attack'] = atr_home_attack
new_attrs['Home_Midfield'] = atr_home_midfield
new_attrs['Home_Defense'] = atr_home_defense
new_attrs['Away_Attack'] = atr_away_attack
new_attrs['Away_Midfield'] = atr_away_midfield
new_attrs['Away_Defense'] = atr_away_defense

Thêm các attributes cho mỗi match

In [148]:
match_merge_desc_new = pd.merge(match_merge_desc, new_attrs, on='Match_Id', how='inner')
match_merge_desc_new

,Match_Id,Match_Date,Home_Team,Home_Manager,Home_Captain,Home_Formation,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,...,Away_Att_Take_Ons,Away_Succ_Take_Ons,Home_Score,Away_Score,Home_Attack,Home_Midfield,Home_Defense,Away_Attack,Away_Midfield,Away_Defense
0,8c6293a3,2023-10-23,Tottenham Hotspur,Ange Postecoglou,Son Heung-min,4231,65.0,9.0,8.5,21.0,...,15.0,8.5,2,0,78.909091,79.636364,77.000000,74.400000,76.588235,74.875000
1,7efcc598,2023-10-22,Aston Villa,Unai Emery,John McGinn,442,46.0,14.0,5.5,18.5,...,11.5,7.5,4,1,72.714286,77.944444,78.333333,74.000000,78.916667,77.800000
2,d95b42eb,2023-10-21,Sheffield United,Paul Heckingbottom,Oliver Norwood,442,44.0,9.5,4.0,14.5,...,20.0,10.5,1,2,69.400000,71.615385,69.181818,75.833333,79.588235,79.800000
3,21625dde,2023-10-21,Newcastle United,Eddie Howe,Jamaal Lascelles,433,58.5,12.5,3.5,15.5,...,20.0,9.5,4,0,78.100000,80.888889,75.272727,72.833333,71.333333,76.857143
4,e747ddb3,2023-10-21,Liverpool,Jürgen Klopp,Virgil van Dijk,433,45.0,18.5,3.0,9.5,...,25.0,11.0,2,0,82.800000,80.846154,79.125000,74.800000,75.200000,74.692308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1929,f74a4680,2018-09-01,Manchester City,Pep Guardiola,David Silva,4132,73.5,8.5,9.5,27.0,...,8.5,2.5,2,1,85.250000,83.250000,83.000000,75.750000,73.230769,73.333333
1930,95fc9c84,2018-09-01,Chelsea,Maurizio Sarri,César Azpilicueta,433,71.0,10.0,5.0,19.0,...,18.5,9.0,2,0,85.500000,82.000000,81.750000,74.500000,75.538462,74.666667
1931,51055c21,2018-09-01,Brighton & Hove Albion,Chris Hughton,Lewis Dunk,4411,32.5,15.0,4.0,12.0,...,12.5,7.5,2,2,76.000000,74.357143,75.666667,75.250000,76.909091,73.000000
1932,db5e61cc,2018-08-25,Liverpool,Jürgen Klopp,James Milner,433,63.5,13.5,6.0,22.0,...,7.0,4.5,1,0,84.833333,81.555556,80.500000,76.000000,74.357143,75.000000
1933,a25a3f33,2018-08-25,Wolverhampton Wanderers,Nuno Espírito Santo,Conor Coady,343,57.5,8.0,6.0,27.0,...,19.0,13.5,1,1,74.428571,75.200000,73.222222,86.000000,85.300000,83.000000

Sắp xếp các attribute tạo thành một Dataset dùng cho model, xuất ra CSV

In [149]:
match_merge_desc_new = match_merge_desc_new.loc[:,['Match_Id', 'Match_Date',
                                'Home_Team', 'Home_Manager', 'Home_Captain',
                                'Home_Formation', 'Home_Possession', 'Home_Fouls', 'Home_Corners', 'Home_Crosses',
                                'Home_Aerials_Won', 'Home_Clearances', 'Home_Offsides', 'Home_Goal_Kicks',
                                'Home_Throw_Ins', 'Home_Long_Balls', 'Home_Total_Players_Stats', 'Home_Minutes',
                                'Home_Gls', 'Home_Ast', 'Home_PK', 'Home_PK_Att',
                                'Home_Sh','Home_SoT', 'Home_CrdY', 'Home_CrdR',
                                'Home_Touches','Home_Tkl','Home_Int','Home_Blocks',
                                'Home_xG','Home_npxG', 'Home_xAG',
                                'Home_SCA', 'Home_GCA',
                                'Home_Cmp_Passes', 'Home_Att_Passes', 'Home_Cmp_percent_Passes', 'Home_PrgP_Passes',
                                'Home_Carries_Carries', 'Home_PrgC_Carries', 
                                'Home_Att_Take_Ons', 'Home_Succ_Take_Ons',
                                'Away_Team', 'Away_Manager', 'Away_Captain',
                                'Away_Formation', 'Away_Possession', 'Away_Fouls', 'Away_Corners', 'Away_Crosses',
                                'Away_Aerials_Won', 'Away_Clearances', 'Away_Offsides', 'Away_Goal_Kicks',
                                'Away_Throw_Ins', 'Away_Long_Balls', 'Away_Total_Players_Stats', 'Away_Minutes',
                                'Away_Gls', 'Away_Ast', 'Away_PK', 'Away_PK_Att',
                                'Away_Sh','Away_SoT', 'Away_CrdY', 'Away_CrdR',
                                'Away_Touches','Away_Tkl','Away_Int','Away_Blocks',
                                'Away_xG','Away_npxG', 'Away_xAG',
                                'Away_SCA', 'Away_GCA',
                                'Away_Cmp_Passes', 'Away_Att_Passes', 'Away_Cmp_percent_Passes', 'Away_PrgP_Passes',
                                'Away_Carries_Carries', 'Away_PrgC_Carries', 
                                'Away_Att_Take_Ons', 'Away_Succ_Take_Ons',
                                'Home_Attack', 'Home_Midfield', 'Home_Defense', 
                                'Away_Attack', 'Away_Midfield', 'Away_Defense', 
                                'Home_Score','Away_Score']]
match_merge_desc_new

,Match_Id,Match_Date,Home_Team,Home_Manager,Home_Captain,Home_Formation,Home_Possession,Home_Fouls,Home_Corners,Home_Crosses,...,Away_Cmp_Passes,Away_Att_Passes,Away_Cmp_percent_Passes,Away_PrgP_Passes,Away_Carries_Carries,Away_PrgC_Carries,Away_Att_Take_Ons,Away_Succ_Take_Ons,Home_Score,Away_Score
0,db4d7668,2019-05-12,Watford,Javi Gracia,Troy Deeney,4222,49,10,7,22,...,426,492,86.6,32,347,31,28,23,1,4
1,d4360fcd,2020-07-26,Burnley,Sean Dyche,James Tarkowski,442,55,11,6,37,...,279,377,74.0,29,288,18,11,5,1,2
2,b6b1209d,2020-07-26,Newcastle United,Steve Bruce,Jonjo Shelvey,352,26,11,2,7,...,742,844,87.9,59,780,21,30,13,1,3
3,a3f59c8e,2020-07-26,West Ham United,David Moyes,Mark Noble,4231,62,16,0,10,...,217,323,67.2,18,193,11,9,3,1,1
4,9cca4ba0,2020-07-26,Chelsea,Frank Lampard,César Azpilicueta,343,62,10,3,11,...,281,410,68.5,29,232,9,23,8,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,82702941,2022-08-06,Leeds United,Jesse Marsch,Patrick Bamford,4231,40,13,6,20,...,502,597,84.1,44,507,20,41,25,2,1
1986,1ac96eb4,2022-08-06,Newcastle United,Eddie Howe,Kieran Trippier,433,61,9,11,25,...,243,342,71.1,16,202,12,17,5,2,0
1987,09d8a999,2022-08-06,Tottenham Hotspur,Antonio Conte,Hugo Lloris,343,58,11,10,24,...,351,445,78.9,31,299,12,18,9,4,1
1988,6713c1dc,2022-08-06,Fulham,Marco Silva,Tim Ream,4231,33,7,4,19,...,514,675,76.1,53,418,11,17,4,2,2
1989,e62f6e78,2022-08-05,Crystal Palace,Patrick Vieira,Marc Guéhi,4231,56,16,3,19,...,378,469,80.6,40,359,15,17,13,0,2

In [150]:
match_merge_desc_new.to_csv('./dataset_model/matchs_dataset_model.csv', index=False)